### PR TITLE
fix(sasjs-run): Change access token mechanism, store log to file

### PR DESCRIPTION
**Pull request by krishna-acondy**
## Issue

Fixes https://github.com/sasjs/cli/issues/128.

## Intent

Improve the `sasjs run` command to address the issues described in https://github.com/sasjs/cli/issues/128.

## Implementation

* Migrated to the access token mechanism used by the other commands - fetch it from the `.env` file.
* Saved execution log to a `sasjs-run-{timestamp}.log` file.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
- [x] All CI checks are green.
- [x] JSDoc comments have been added or updated.

### CODE REVIEW

**Review by allanbowe — APPROVED** [review]

**Comment by allanbowe** [comment]
Nice.  I wonder if we should have an additional checkbox (`Automated tests have been added or updated`)

**Comment by krishna-acondy** [comment]
By automated tests, do you mean the command tests that run as part of the build? The issue with that, is that we can't run commands that need to make requests to the server yet.

**Comment by allanbowe** [comment]
Understood.  I saw you did make a unit test in this PR.  There was a discussion last week that every (non trivial) PR should contain some kind of update to a test (even if it was an unrelated test) to ensure we keep the focus on testing.  Off topic for this thread but maybe it should be in our PR template.

**Comment by krishna-acondy** [comment]
I thought that between 'All unit tests are passing' and 'Any new functionality has been unit tested', we've covered all scenarios. Haven't we?

**Review by allanbowe — APPROVED** [review]

**Pull request merged**
